<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>WLMServer</RootNamespace>
    <AssemblyName>WLMServer</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RuntimeIdentifiers>osx-arm64;osx-x64;linux-x64;linux-arm64;win-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Config\Properties.cs" />
    <Compile Include="Database\AccountManager.cs" />
    <Compile Include="Database\DBConnection.cs" />
    <Compile Include="Database\PasswordEncrypter.cs" />
    <Compile Include="Data\ContactRegister.cs" />
    <Compile Include="Network\WebServer.cs" />
    <Compile Include="Network\SignUpPage.cs" />
    <Compile Include="Network\PacketHandler.cs" />
    <Compile Include="Network\PacketHandling\AddNewContact.cs" />
    <Compile Include="Network\PacketHandling\Authentication.cs" />
    <Compile Include="Network\PacketHandling\AddNewContactResponse.cs" />
    <Compile Include="Network\PacketHandling\ChangeUsername.cs" />
    <Compile Include="Network\PacketHandling\DeleteAndBlockContact.cs" />
    <Compile Include="Network\PacketHandling\PersonalUserUpdate.cs" />
    <Compile Include="Network\PacketHandling\TransferCall.cs" />
    <Compile Include="Network\PacketHandling\TransferFile.cs" />
    <Compile Include="Network\PacketHandling\TransferMessage.cs" />
    <Compile Include="Network\PacketHandling\TransferNudge.cs" />
    <Compile Include="Network\PacketHandling\TransferVoice.cs" />
    <Compile Include="Network\PacketHandling\ServerInformation.cs" />
    <Compile Include="Network\PacketHandling\TransferWritingStatus.cs" />
    <Compile Include="Network\Server.cs" />
    <Compile Include="Network\UserData\ConnectedUser.cs" />
    <Compile Include="Network\UserData\Contact.cs" />
    <Compile Include="Network\UserData\ContactList.cs" />
    <Compile Include="Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Messenger.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.1.0" />
    <ProjectReference Include="..\WLMData\WLMData.csproj" />
    <ProjectReference Include="..\WLMNet\WLMNet.csproj" />
  </ItemGroup>

</Project>
