<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>WLMData</RootNamespace>
    <AssemblyName>WLMData</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Data\Deserialize.cs" />
    <Compile Include="Data\Packets\FileTransfer.cs" />
    <Compile Include="Data\Packets\FriendRequestResponse.cs" />
    <Compile Include="Data\Packets\LoginRequest.cs" />
    <Compile Include="Data\Packets\LoginResult.cs" />
    <Compile Include="Data\Packets\Message.cs" />
    <Compile Include="Data\Packets\UserInfo.cs" />
    <Compile Include="Data\Packets\WritingStatus.cs" />
    <Compile Include="Data\Serializer.cs" />
    <Compile Include="Enums\FriendRequestResponseCode.cs" />
    <Compile Include="Enums\PacketName.cs" />
    <Compile Include="Enums\UserStatus.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="protobuf-net" Version="3.2.30" />
    <ProjectReference Include="..\WLMNet\WLMNet.csproj" />
  </ItemGroup>

</Project>
